chartConfig:
  config:
    label: Papers
    selectedField: dim_research_papers_paper_count
    showBigNumberLabel: true
    style: K
  type: big_number
contentType: chart
dashboardSlug: research-overview
metricQuery:
  dimensions: []
  exploreName: dim_research_papers
  filters: {}
  limit: 1
  metrics:
    - dim_research_papers_paper_count
  sorts: []
  tableCalculations: []
name: Papers
slug: research-paper-count
spaceSlug: shared
tableName: dim_research_papers
version: 1
