disabled: no

discoverer:
  docker:
    address: unix:///var/run/docker.sock
    timeout: 2s

services:
  - id: metadata-postgres
    match: >-
      {{ and
        (eq .PrivatePort "5432")
        (eq .PortProtocol "tcp")
        (hasKey .Labels "com.docker.compose.project")
        (eq (index .Labels "com.docker.compose.project") "metadata-postgres")
        (hasKey .Labels "com.docker.compose.service")
        (eq (index .Labels "com.docker.compose.service") "metadata-postgres")
      }}
    config_template: |
      module: postgres
      name: metadata
      update_every: 10
      dsn: 'postgresql://lakehouse_monitor@{{.Address}}/postgres?sslmode=disable&passfile=/run/secrets/postgres_pgpass'
      collect_databases_matching: 'postgres airflow lightdash t0_trading'
