chartConfig:
  config:
    label: Push events
    selectedField: fct_repository_activity_daily_total_push_events
    showBigNumberLabel: true
    style: M
  type: big_number
contentType: chart
dashboardSlug: engineering-overview
metricQuery:
  dimensions: []
  exploreName: fct_repository_activity_daily
  filters: {}
  limit: 1
  metrics:
    - fct_repository_activity_daily_total_push_events
  sorts: []
  tableCalculations: []
name: Push events
slug: engineering-push-events
spaceSlug: shared
tableName: fct_repository_activity_daily
version: 1
