services:
  catalog:
    image: tabulario/iceberg-rest:0.6.0
    container_name: iceberg-rest-catalog
    user: "1000:1000"
    ports:
      - "8181:8181"
    environment:
      # Sử dụng JDBC SQLite làm catalog database backend với chế độ WAL và busy_timeout
      CATALOG_CATALOG_IMPL: org.apache.iceberg.jdbc.JdbcCatalog
      CATALOG_URI: jdbc:sqlite:/home/iceberg/data/iceberg_catalog.db?journal_mode=WAL&busy_timeout=10000
      CATALOG_JDBC_USER: user
      CATALOG_JDBC_PASSWORD: password
      CATALOG_WAREHOUSE: file://${HOME}/projects/mini-lakehouse/warehouse
      CATALOG_IO_IMPL: org.apache.iceberg.io.ResolvingFileIO
    volumes:
      - ./catalog-data:/home/iceberg/data
      - ${HOME}/projects/mini-lakehouse/warehouse:${HOME}/projects/mini-lakehouse/warehouse

  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    container_name: clickhouse-server
    user: "1000:1000"
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: github_lakehouse
      CLICKHOUSE_USER: dev_user
      CLICKHOUSE_PASSWORD: dev_password
    volumes:
      - ./clickhouse-data:/var/lib/clickhouse
      - ${HOME}/projects/mini-lakehouse/warehouse:/var/lib/clickhouse/user_files/warehouse
