connector.name=iceberg
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=http://catalog:8181/api/catalog
iceberg.rest-catalog.warehouse=prod
iceberg.rest-catalog.security=OAUTH2
iceberg.rest-catalog.oauth2.credential=root:secretpassword
iceberg.rest-catalog.oauth2.scope=PRINCIPAL_ROLE:ALL

# Cấu hình chính xác endpoint sinh Token OAuth2 của Polaris
iceberg.rest-catalog.oauth2.server-uri=http://catalog:8181/api/catalog/v1/oauth/tokens

# Bật tính năng nested namespace để Trino ánh xạ chính xác các schema phân cấp của Polaris
iceberg.rest-catalog.nested-namespace-enabled=true

# Tắt credential vending nội bộ để Trino kết nối trực tiếp S3 tĩnh
iceberg.rest-catalog.vended-credentials-enabled=false

# Cấu hình lưu trữ S3 trực tiếp trỏ đến MinIO AIStor
fs.s3.enabled=true
s3.endpoint=http://aistor:9000
s3.aws-access-key=any_key
s3.aws-secret-key=any_secret
s3.path-style-access=true
s3.region=us-east-1
