select
    schema_version,
    decision_version,
    decision_configuration_sha256,
    strategy,
    strategy_version,
    strategy_configuration_sha256,
    outcome_version,
    outcome_configuration_sha256,
    feature_version,
    feature_configuration_sha256,
    feature_snapshot_sha256,
    strategy_score_sha256,
    symbol,
    trade_date,
    decision_at,
    market_session,
    horizon_seconds,
    signed_score,
    minimum_strength,
    action,
    cast(json_parse(decision_reasons_json) as array(varchar)) as decision_reasons,
    processed_at,
    decision_sha256
from {{ source('t0_trading', 'shadow_decisions') }}
