jobs:
  - name: lakehouse
    update_every: 10
    include:
      - docker.service
      - containerd.service
      - tailscaled.service
      - systemd-journald.service
      - systemd-timesyncd.service
      - lakehouse-metadata-backup.service
      - lakehouse-metadata-backup.timer
