name: "analytics"
version: "0.3.0"
config-version: 2
profile: "analytics"
require-dbt-version: [">=1.12.0", "<1.13.0"]

model-paths: ["models"]

clean-targets:
  - "target"
  - "dbt_packages"

flags:
  send_anonymous_usage_stats: false
  require_certificate_validation: true

models:
  analytics:
    +persist_docs:
      relation: true
      columns: true
    +meta:
      owner: engineering-analytics
      contact: baokdl2226@gmail.com

    staging:
      +materialized: ephemeral
      +tags: ["staging", "github"]

    intermediate:
      +materialized: ephemeral
      +tags: ["intermediate", "engineering"]

    marts:
      +materialized: table
      +table_type: iceberg
      engineering:
        +tags: ["mart", "engineering"]
        +meta:
          business_owner: engineering
