mini_lakehouse:
  target: "{{ env_var('DBT_TARGET', 'local') }}"
  outputs:
    local:
      type: trino
      method: none
      host: "{{ env_var('LAKEHOUSE_TRINO__HOST', 'localhost') }}"
      port: "{{ env_var('LAKEHOUSE_TRINO__PORT', '8080') | int }}"
      user: "{{ env_var('LAKEHOUSE_TRINO__USER', 'lakehouse') }}"
      catalog: "{{ env_var('LAKEHOUSE_TRINO__CATALOG', 'prod') }}"
      schema: analytics.engineering
      http_scheme: "{{ env_var('LAKEHOUSE_TRINO__HTTP_SCHEME', 'http') }}"
      cert: true
      threads: "{{ env_var('DBT_THREADS', '4') | int }}"
      timezone: UTC
      retries: 2
      session_properties:
        query_max_run_time: 30m
