chartConfig:
  config:
    label: Mean quoted spread (bps)
    selectedField: fct_trading_backtest_observations_average_spread_bps
    showBigNumberLabel: true
  type: big_number
contentType: chart
dashboardSlug: trading-overview
metricQuery:
  dimensions: []
  exploreName: fct_trading_backtest_observations
  filters: {}
  limit: 1
  metrics:
    - fct_trading_backtest_observations_average_spread_bps
  sorts: []
  tableCalculations: []
name: Mean quoted spread
slug: trading-average-spread
spaceSlug: trading
tableName: fct_trading_backtest_observations
version: 1
