chartConfig:
  config:
    label: Positive gross markouts (%)
    selectedField: fct_trading_backtest_observations_positive_gross_markout_rate_pct
    showBigNumberLabel: true
  type: big_number
contentType: chart
dashboardSlug: trading-overview
metricQuery:
  dimensions: []
  exploreName: fct_trading_backtest_observations
  filters: {}
  limit: 1
  metrics:
    - fct_trading_backtest_observations_positive_gross_markout_rate_pct
  sorts: []
  tableCalculations: []
name: Positive gross markouts
slug: trading-positive-gross-markout-rate
spaceSlug: trading
tableName: fct_trading_backtest_observations
version: 1
