[db]
    db = dbengine
    update every = 1
    storage tiers = 3
    dbengine tier 0 retention size = 1GiB
    dbengine tier 0 retention time = 7d
    dbengine tier 1 retention size = 1GiB
    dbengine tier 1 retention time = 90d
    dbengine tier 2 retention size = 512MiB
    dbengine tier 2 retention time = 1y

[web]
    bind to = 127.0.0.1:19999
    bearer token protection = no
    allow connections from = *
    allow connections by dns = no
    allow dashboard from = *
    allow dashboard by dns = no
    allow mcp from = *
    allow mcp by dns = no
    allow management from = *
    allow management by dns = no
    allow badges from = !*
    allow badges by dns = no
    allow netdata.conf from = !*
    allow netdata.conf by dns = no
    allow streaming from = !*
    allow streaming by dns = no

[health]
    enabled = yes

[ml]
    enabled = yes

[registry]
    enabled = no

[plugins]
    idlejitter = no
    netdata pulse = yes
    profile = no
    tc = no
    diskspace = yes
    proc = yes
    cgroups = yes
    timex = yes
    enable running new plugins = no
    slabinfo = no
    freeipmi = no
    statsd = yes
    debugfs = no
    python.d = no
    network-viewer = yes
    perf = no
    otel-signal-viewer = no
    systemd-units = no
    go.d = yes
    charts.d = no
    ioping = no
    apps = no
    systemd-journal = yes
    otel = no

[plugin:cgroups]
    enable by default cgroups matching = */docker-*.scope /system.slice/docker.service /system.slice/containerd.service /system.slice/tailscaled.service !*
    enable by default cgroups names matching = !netdata-netdata-1 !cloudflare-cloudflare-tunnel-1 *
    run script to rename cgroups matching = *docker* !*
    cgroups to match as systemd services = /system.slice/docker.service /system.slice/containerd.service /system.slice/tailscaled.service !*

[plugin:proc]
    /proc/net/stat/conntrack = no
    /proc/net/sctp/snmp = no
    /proc/net/ip_vs/stats = no
    /proc/net/stat/synproxy = no
    /proc/net/rpc/nfsd = no
    /proc/net/rpc/nfs = no
    /proc/spl/kstat/zfs/arcstats = no
    /sys/fs/btrfs = no

[plugin:proc:diskspace]
    exclude space metrics on paths = /dev /dev/shm /proc/* /sys/* /var/run/user/* /run/lock /run/user/* /snap/* /var/lib/docker/* /var/lib/containers/storage/* /run/credentials/* /run/containerd/* /run/docker/netns/* /rpool /rpool/*

[statsd]
    enabled = yes
    update every (flushInterval) = 1s
    create private charts for metrics matching = !*
    max private charts hard limit = 100
    histograms and timers percentile (percentThreshold) = 95
    add dimension for number of events received = no
    gaps on gauges (deleteGauges) = yes
    gaps on counters (deleteCounters) = yes
    gaps on histograms (deleteHistograms) = yes
    gaps on timers (deleteTimers) = yes
    bind to = udp:172.24.0.1:8125

[host labels]
    environment = dev
    project = mini-lakehouse
    provider = oci
    region = ap-singapore-1
    role = services
