chartConfig:
  config:
    eChartsConfig:
      series:
        - color: "#7048E8"
          encode:
            xRef:
              field: fct_research_publications_daily_primary_category
            yRef:
              field: fct_research_publications_daily_total_papers
          name: Papers
          type: bar
      yAxis:
        - min: "0"
          minInterval: 1
    layout:
      flipAxes: true
      xField: fct_research_publications_daily_primary_category
      yField:
        - fct_research_publications_daily_total_papers
  type: cartesian
contentType: chart
dashboardSlug: research-overview
metricQuery:
  dimensions:
    - fct_research_publications_daily_primary_category
  exploreName: fct_research_publications_daily
  filters: {}
  limit: 10
  metrics:
    - fct_research_publications_daily_total_papers
  sorts:
    - descending: true
      fieldId: fct_research_publications_daily_total_papers
  tableCalculations: []
name: Top primary categories
slug: research-top-categories
spaceSlug: shared
tableName: fct_research_publications_daily
version: 1
